######################## default configuration ####################
baseURL = "https://dev.platolearning.ca"
title = "Plato Learning | Luscinia"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "platolearning" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Plato Learning Services is a tutoring service provided by Luscinia Enterprises Assn."
author = "Luscinia Enterprises Assn."
# contact info
#address = "#701-1288 Marinaside Cres. Vancouver, BC"
mobile = "+1 (844) 928-3292"
email = "plato@luscinia.ca"
# contact form action
# contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "G-45NJK0R9NN" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = false
# gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
# map_latitude = "51.5223477"
# map_longitude = "-0.1622023"
# map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = false
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/lusciniaenterprises"


[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/luscinia-enterprises"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://linkedin.com/company/luscinia-enterprises"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 Luscinia Enterprises Assn."



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 1

[[Languages.en.menu.main]]
name = "Scholarships"
url = "scholarship"
weight = 2

[[Languages.en.menu.main]]
name = "Our Tutors"
url = "teacher"
weight = 3

[[Languages.en.menu.main]]
name = "More"
hasChildren = true
weight = 4

  [[Languages.en.menu.main]]
  parent = "More"
  name = "Public Notices"
  url = "notice"

  [[Languages.en.menu.main]]
  parent = "More"
  name = "Upcoming Events"
  url = "event"
  
[[Languages.en.menu.main]]
name = "blog"
url = "blog"
weight = 5


# footer menu

[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher"

[[Languages.en.menu.footer]]
name = "notice"
url = "notice"

[[Languages.en.menu.footer]]
name = "event"
url = "event"

[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.en.menu.footer]]
name = "research"
url = "research"
